spring:
    datasource:
        name: test
        url: jdbc:mysql://id:3306/db2017_java_kq?useUnicode=true&characterEncoding=UTF-8
        username: username
        password: password
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            maxActive: 50
            filters: stat,wall,log4j
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20


mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.test.model

pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
mapper:
    mappers: com.test.core.utils.TkMapper
    not-empty: false
    i-d-e-n-t-i-t-y: MYSQL
